# Generated by Django 5.0.14 on 2026-03-06 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EdgarCompany",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(db_index=True, max_length=16, unique=True)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("cik", models.CharField(db_index=True, max_length=10)),
                ("is_sp500", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
        migrations.CreateModel(
            name="EdgarDocument",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("facts", "Company Facts"),
                            ("filings", "Filings"),
                            ("company_concept", "Company Concept"),
                            ("full_text_search", "Full Text Search"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("params", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("source_url", models.URLField(blank=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "http_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("attempt_count", models.PositiveIntegerField(default=1)),
                ("success", models.BooleanField(db_index=True, default=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="edgar.edgarcompany",
                    ),
                ),
            ],
            options={
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["company", "kind", "-fetched_at"],
                        name="edgar_edgar_company_7f23eb_idx",
                    ),
                    models.Index(
                        fields=["kind", "success"], name="edgar_edgar_kind_67b515_idx"
                    ),
                ],
            },
        ),
    ]
