# Generated by Django 6.0.3 on 2026-03-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edgar", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edgarcompany",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="edgardocument",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
