# Generated by Django 6.0.3 on 2026-03-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edgar", "0002_alter_edgarcompany_id_alter_edgardocument_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdgarFundamental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taxonomy", models.CharField(db_index=True, max_length=64)),
                ("tag", models.CharField(db_index=True, max_length=128)),
                ("unit", models.CharField(db_index=True, max_length=32)),
                ("end_date", models.DateField(db_index=True)),
                ("filed_date", models.DateField(blank=True, db_index=True, null=True)),
                ("value", models.FloatField()),
                ("form", models.CharField(blank=True, db_index=True, max_length=32)),
                ("fiscal_year", models.IntegerField(blank=True, null=True)),
                ("fiscal_period", models.CharField(blank=True, max_length=16)),
                (
                    "accession",
                    models.CharField(blank=True, db_index=True, max_length=24),
                ),
                ("frame", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fundamentals",
                        to="edgar.edgarcompany",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fundamental_points",
                        to="edgar.edgardocument",
                    ),
                ),
            ],
            options={
                "ordering": ["company__ticker", "taxonomy", "tag", "end_date"],
                "indexes": [
                    models.Index(
                        fields=["company", "end_date"],
                        name="edgar_edgar_company_76b4a3_idx",
                    ),
                    models.Index(
                        fields=["company", "taxonomy", "tag", "end_date"],
                        name="edgar_edgar_company_7fff5b_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "company",
                            "taxonomy",
                            "tag",
                            "unit",
                            "end_date",
                            "filed_date",
                            "form",
                            "fiscal_year",
                            "fiscal_period",
                            "accession",
                            "frame",
                        ),
                        name="edgar_unique_fundamental_point",
                    )
                ],
            },
        ),
    ]
