# Generated by Django 6.0.3 on 2026-03-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edgar", "0003_edgarfundamental"),
    ]

    operations = [
        migrations.CreateModel(
            name="EdgarMetricMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric_key", models.CharField(db_index=True, max_length=64)),
                ("taxonomy", models.CharField(default="us-gaap", max_length=64)),
                ("tag", models.CharField(max_length=128)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("heuristic", "Heuristic"),
                            ("openai", "OpenAI"),
                            ("manual", "Manual"),
                        ],
                        default="heuristic",
                        max_length=16,
                    ),
                ),
                ("confidence", models.FloatField(default=0.0)),
                ("rationale", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metric_mappings",
                        to="edgar.edgarcompany",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "metric_key"),
                        name="edgar_unique_company_metric_mapping",
                    )
                ],
            },
        ),
    ]
