# Generated by Django 6.0.3 on 2026-03-07 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edgar", "0004_edgarmetricmapping"),
    ]

    operations = [
        migrations.AddField(
            model_name="edgarcompany",
            name="sector",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="edgarcompany",
            name="sub_industry",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name="BuffettScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("overall_score", models.FloatField()),
                ("roe_avg", models.FloatField(blank=True, null=True)),
                ("roe_score", models.FloatField(default=0)),
                ("debt_to_equity", models.FloatField(blank=True, null=True)),
                ("debt_score", models.FloatField(default=0)),
                ("margin_avg", models.FloatField(blank=True, null=True)),
                ("margin_score", models.FloatField(default=0)),
                ("earnings_growth", models.FloatField(blank=True, null=True)),
                ("earnings_growth_score", models.FloatField(default=0)),
                ("fcf_avg", models.FloatField(blank=True, null=True)),
                ("fcf_score", models.FloatField(default=0)),
                ("intrinsic_value", models.FloatField(blank=True, null=True)),
                ("current_price", models.FloatField(blank=True, null=True)),
                ("margin_of_safety", models.FloatField(blank=True, null=True)),
                ("valuation_score", models.FloatField(default=0)),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buffett_scores",
                        to="edgar.edgarcompany",
                    ),
                ),
            ],
            options={
                "ordering": ["-computed_at"],
                "get_latest_by": "computed_at",
            },
        ),
        migrations.CreateModel(
            name="StockPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("open", models.FloatField(blank=True, null=True)),
                ("high", models.FloatField(blank=True, null=True)),
                ("low", models.FloatField(blank=True, null=True)),
                ("close", models.FloatField()),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                ("market_cap", models.FloatField(blank=True, null=True)),
                ("fetched_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="edgar.edgarcompany",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "date"), name="unique_stock_price_per_day"
                    )
                ],
            },
        ),
    ]
