"""Backtest QQQ DCA with leveraged short overlays during ML risk-off regimes.

This is research tooling, not investment advice. It consumes the ML regime
signals generated by tools/qqq_macro_ml_regime_analysis.py and tests whether
shorting QQQ shares can replace the collar hedge idea.
"""

from __future__ import annotations

import argparse
import json
import math
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_DATASET_PATH = ROOT / "reports" / "qqq_macro_ml_regime_analysis" / "aligned_daily_dataset.csv"
DEFAULT_SIGNAL_PATH = ROOT / "reports" / "qqq_macro_ml_regime_analysis" / "walkforward_allocation_signal.csv"
DEFAULT_OUT_DIR = ROOT / "reports" / "qqq_macro_short_overlay_backtest"
TRADING_DAYS_PER_YEAR = 252


@dataclass(frozen=True)
class StrategyConfig:
    name: str
    mode: str
    leverage: float = 0.0
    hedge_budget_pct: float = 0.10
    max_short_exposure: float = 1.0
    use_drawdown_ladder: bool = True


def _json_default(obj: Any) -> Any:
    if isinstance(obj, pd.Timestamp):
        return obj.isoformat()
    if isinstance(obj, np.integer):
        return int(obj)
    if isinstance(obj, np.floating):
        return float(obj)
    if isinstance(obj, np.bool_):
        return bool(obj)
    if pd.isna(obj):
        return None
    raise TypeError(f"Object of type {type(obj).__name__} is not JSON serializable")


def _xirr(cashflows: list[tuple[pd.Timestamp, float]]) -> float:
    flows = [(pd.Timestamp(date), float(amount)) for date, amount in cashflows if np.isfinite(amount)]
    if not flows or not any(amount < 0 for _, amount in flows) or not any(amount > 0 for _, amount in flows):
        return np.nan
    start = flows[0][0]

    def npv(rate: float) -> float:
        total = 0.0
        for date, amount in flows:
            years = max((date - start).days / 365.25, 0.0)
            total += amount / ((1.0 + rate) ** years)
        return total

    low, high = -0.999, 10.0
    low_npv, high_npv = npv(low), npv(high)
    if not np.isfinite(low_npv) or not np.isfinite(high_npv) or low_npv * high_npv > 0:
        return np.nan
    for _ in range(120):
        mid = (low + high) / 2.0
        mid_npv = npv(mid)
        if abs(mid_npv) < 1e-7:
            return mid
        if low_npv * mid_npv <= 0:
            high = mid
            high_npv = mid_npv
        else:
            low = mid
            low_npv = mid_npv
    return (low + high) / 2.0


def load_inputs(dataset_path: Path, signal_path: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    if not dataset_path.exists():
        raise FileNotFoundError(f"Missing dataset: {dataset_path}. Run qqq_macro_ml_regime_analysis.py first.")
    if not signal_path.exists():
        raise FileNotFoundError(f"Missing signal file: {signal_path}. Run qqq_macro_ml_regime_analysis.py first.")
    dataset = pd.read_csv(dataset_path, parse_dates=["date"]).set_index("date").sort_index()
    signals = pd.read_csv(signal_path, parse_dates=["date"]).set_index("date").sort_index()
    required_dataset = {"qqq_close", "qqq_drawdown_252d"}
    required_signal = {
        "risk_off_probability",
        "jump_in_probability",
        "latent_sentiment_index",
        "gmm_regime",
        "target_equity_allocation",
        "signal",
    }
    missing_dataset = required_dataset - set(dataset.columns)
    missing_signal = required_signal - set(signals.columns)
    if missing_dataset:
        raise ValueError(f"Dataset missing columns: {sorted(missing_dataset)}")
    if missing_signal:
        raise ValueError(f"Signal file missing columns: {sorted(missing_signal)}")
    return dataset, signals


def shifted_daily_signals(signals: pd.DataFrame, index: pd.DatetimeIndex) -> pd.DataFrame:
    monthly = signals.copy()
    monthly["sentiment_improving"] = monthly["latent_sentiment_index"].diff() > 0.0
    daily = monthly.reindex(monthly.index.union(index)).sort_index().ffill().reindex(index)
    return daily.shift(1)


def build_targets(dataset: pd.DataFrame, signals: pd.DataFrame, config: StrategyConfig) -> pd.DataFrame:
    index = dataset.index
    daily = shifted_daily_signals(signals, index)
    out = pd.DataFrame(index=index)

    if config.mode == "plain":
        out["long_exposure"] = 1.0
        out["short_exposure"] = 0.0
        out["hedge_active"] = False
        out["execution_state"] = "plain_dca"
        return out

    base_long = pd.to_numeric(daily["target_equity_allocation"], errors="coerce")
    base_long = base_long.clip(lower=0.0, upper=1.0)
    signal = daily["signal"].fillna("insufficient_walkforward_history").astype(str)
    risk_off = signal.eq("risk_off_reserve_cash")
    jump_in = signal.eq("jump_in_full_allocation")
    jump_exit = (
        (pd.to_numeric(daily["jump_in_probability"], errors="coerce") >= 0.70)
        & (pd.to_numeric(daily["risk_off_probability"], errors="coerce") < 0.45)
        & (daily["sentiment_improving"].map(lambda value: bool(value) if pd.notna(value) else False))
    )

    long_target = base_long.copy()
    long_target = long_target.fillna(1.0)
    if config.use_drawdown_ladder:
        drawdown = pd.to_numeric(dataset["qqq_drawdown_252d"], errors="coerce")
        long_target.loc[risk_off & (drawdown <= -0.15)] = np.maximum(long_target.loc[risk_off & (drawdown <= -0.15)], 0.40)
        long_target.loc[risk_off & (drawdown <= -0.25)] = np.maximum(long_target.loc[risk_off & (drawdown <= -0.25)], 0.60)
        long_target.loc[risk_off & (drawdown <= -0.35)] = np.maximum(long_target.loc[risk_off & (drawdown <= -0.35)], 0.80)
    long_target.loc[jump_exit] = np.maximum(long_target.loc[jump_exit], 0.70)
    long_target.loc[jump_in] = 1.0
    long_target = long_target.clip(lower=0.0, upper=1.0)

    hedge_active = risk_off & ~jump_exit
    if config.mode == "regime":
        short_target = pd.Series(0.0, index=index)
    elif config.mode == "budget_short":
        short_target = pd.Series(0.0, index=index)
        short_target.loc[hedge_active] = min(config.hedge_budget_pct * config.leverage, config.max_short_exposure)
    elif config.mode == "reserve_short":
        short_target = pd.Series(0.0, index=index)
        reserve = (1.0 - long_target).clip(lower=0.0)
        short_target.loc[hedge_active] = np.minimum(reserve.loc[hedge_active] * config.leverage, config.max_short_exposure)
    else:
        raise ValueError(f"Unknown strategy mode: {config.mode}")

    execution_state = pd.Series("neutral_or_jump", index=index, dtype=object)
    execution_state.loc[risk_off] = "risk_off"
    execution_state.loc[jump_exit] = "risk_off_hedge_removed_early"
    execution_state.loc[jump_in] = "jump_in"

    out["long_exposure"] = long_target
    out["short_exposure"] = short_target.clip(lower=0.0)
    out["net_exposure"] = out["long_exposure"] - out["short_exposure"]
    out["gross_exposure"] = out["long_exposure"] + out["short_exposure"]
    out["hedge_active"] = hedge_active & (out["short_exposure"] > 0.0)
    out["execution_state"] = execution_state
    return out


def simulate_strategy(
    close: pd.Series,
    targets: pd.DataFrame,
    *,
    name: str,
    start_date: pd.Timestamp,
    initial_capital: float,
    monthly_contribution: float,
    trading_cost_bps: float,
    margin_borrow_rate: float,
    short_borrow_rate: float,
) -> tuple[pd.DataFrame, list[tuple[pd.Timestamp, float]]]:
    price = close[close.index >= start_date].copy()
    target = targets.reindex(price.index).copy()
    returns = price.pct_change().fillna(0.0)
    cost_rate = trading_cost_bps / 10_000.0

    equity = float(initial_capital)
    active_long = 0.0
    active_short = 0.0
    prior_month = None
    cashflows: list[tuple[pd.Timestamp, float]] = [(price.index[0], -float(initial_capital))]
    rows: list[dict[str, Any]] = []
    ruin_date: pd.Timestamp | None = None

    for i, (date, ret) in enumerate(returns.items()):
        month = date.to_period("M")
        if i > 0 and month != prior_month:
            equity += float(monthly_contribution)
            cashflows.append((date, -float(monthly_contribution)))
        prior_month = month

        desired_long = float(target.loc[date, "long_exposure"]) if np.isfinite(target.loc[date, "long_exposure"]) else 1.0
        desired_short = float(target.loc[date, "short_exposure"]) if np.isfinite(target.loc[date, "short_exposure"]) else 0.0
        desired_long = max(desired_long, 0.0)
        desired_short = max(desired_short, 0.0)

        if equity > 0.0:
            turnover = abs(desired_long - active_long) + abs(desired_short - active_short)
            equity -= equity * turnover * cost_rate
            active_long = desired_long
            active_short = desired_short

            gross = active_long + active_short
            margin_cost = max(gross - 1.0, 0.0) * margin_borrow_rate / TRADING_DAYS_PER_YEAR
            short_cost = active_short * short_borrow_rate / TRADING_DAYS_PER_YEAR
            daily_return = active_long * float(ret) - active_short * float(ret) - margin_cost - short_cost
            equity *= 1.0 + daily_return
            if equity <= 0.0 and ruin_date is None:
                equity = 0.0
                active_long = 0.0
                active_short = 0.0
                ruin_date = date

        rows.append(
            {
                "date": date,
                "strategy": name,
                "equity": equity,
                "long_exposure": active_long,
                "short_exposure": active_short,
                "net_exposure": active_long - active_short,
                "gross_exposure": active_long + active_short,
                "hedge_active": bool(target.loc[date, "hedge_active"]) if "hedge_active" in target.columns else False,
                "execution_state": target.loc[date, "execution_state"],
                "ruin_date": ruin_date,
            }
        )

    cashflows.append((price.index[-1], float(max(equity, 0.0))))
    result = pd.DataFrame(rows).set_index("date")
    return result, cashflows


def performance_metrics(curves: dict[str, pd.DataFrame], cashflows: dict[str, list[tuple[pd.Timestamp, float]]]) -> pd.DataFrame:
    rows = []
    for name, curve in curves.items():
        equity = curve["equity"].dropna()
        if equity.empty:
            continue
        returns = equity.pct_change().replace([np.inf, -np.inf], np.nan).dropna()
        drawdown = equity / equity.cummax().replace(0.0, np.nan) - 1.0
        total_contributed = -sum(amount for _, amount in cashflows[name][:-1] if amount < 0.0)
        ruin_values = curve["ruin_date"].dropna()
        rows.append(
            {
                "strategy": name,
                "start": equity.index[0],
                "end": equity.index[-1],
                "final_value": float(equity.iloc[-1]),
                "total_contributed": float(total_contributed),
                "profit": float(equity.iloc[-1] - total_contributed),
                "profit_on_contributed": float(equity.iloc[-1] / total_contributed - 1.0) if total_contributed > 0 else np.nan,
                "xirr": _xirr(cashflows[name]),
                "max_drawdown": float(drawdown.min()),
                "xirr_over_abs_max_drawdown": _xirr(cashflows[name]) / abs(float(drawdown.min()))
                if drawdown.min() < 0.0
                else np.nan,
                "annualized_vol_of_account_returns": float(returns.std() * math.sqrt(TRADING_DAYS_PER_YEAR)) if len(returns) > 2 else np.nan,
                "avg_long_exposure": float(curve["long_exposure"].mean()),
                "avg_short_exposure": float(curve["short_exposure"].mean()),
                "avg_net_exposure": float(curve["net_exposure"].mean()),
                "avg_gross_exposure": float(curve["gross_exposure"].mean()),
                "max_short_exposure": float(curve["short_exposure"].max()),
                "max_gross_exposure": float(curve["gross_exposure"].max()),
                "hedge_active_days_pct": float(curve["hedge_active"].mean()),
                "ruined": bool(not ruin_values.empty),
                "ruin_date": ruin_values.iloc[0] if not ruin_values.empty else pd.NaT,
            }
        )
    return pd.DataFrame(rows).sort_values(["ruined", "final_value"], ascending=[True, False])


def plot_equity(curves: dict[str, pd.DataFrame], path: Path) -> None:
    fig, ax = plt.subplots(figsize=(14, 7))
    for name, curve in curves.items():
        equity = curve["equity"].replace(0.0, np.nan)
        ax.plot(equity.index, equity, linewidth=1.1, label=name)
    ax.set_title("QQQ DCA with leveraged short overlays")
    ax.set_ylabel("Account value, USD")
    ax.set_yscale("log")
    ax.legend(loc="upper left", fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=160)
    plt.close(fig)


def plot_exposures(curves: dict[str, pd.DataFrame], path: Path) -> None:
    fig, ax = plt.subplots(figsize=(14, 7))
    for name, curve in curves.items():
        if "Budget short" in name or name == "Regime DCA, no short":
            ax.plot(curve.index, curve["net_exposure"], linewidth=1.0, label=name)
    ax.axhline(0.0, color="black", linewidth=0.8)
    ax.set_title("Net exposure for conservative short-hedge variants")
    ax.set_ylabel("Net QQQ exposure")
    ax.legend(loc="upper left", fontsize=8)
    fig.tight_layout()
    fig.savefig(path, dpi=160)
    plt.close(fig)


def write_report(
    out_dir: Path,
    metrics: pd.DataFrame,
    latest_targets: pd.DataFrame,
    args: argparse.Namespace,
) -> None:
    lines: list[str] = []
    lines.append("# QQQ Leveraged Short Overlay Backtest")
    lines.append("")
    lines.append("This is research tooling, not investment advice.")
    lines.append("")
    lines.append("## Rules")
    lines.append("")
    lines.append("- Input signal comes from `walkforward_allocation_signal.csv` generated by the macro ML regime analysis.")
    lines.append("- Normal / neutral keeps the model DCA allocation near 70%; jump-in uses 100%.")
    lines.append("- Risk-off starts with the model allocation near 25%, then uses a drawdown ladder: 40% long below -15%, 60% below -25%, 80% below -35% 252-day drawdown.")
    lines.append("- Hedge is removed early when jump-in probability is at least 70%, risk-off probability is below 45%, and latent sentiment is improving.")
    lines.append("- Conservative short overlays use a 10% account hedge budget leveraged 3x/5x/10x, so short exposure is about 30%/50%/100% of account equity.")
    lines.append("- Aggressive reserve overlays short the idle reserve at 3x/5x/10x. These are included to show tail risk, not as a recommended default.")
    lines.append(f"- Trading cost: `{args.trading_cost_bps}` bps per exposure change; margin borrow: `{args.margin_borrow_rate:.1%}`; short borrow: `{args.short_borrow_rate:.1%}`.")
    lines.append("")
    lines.append("## Results")
    lines.append("")
    lines.append("| Strategy | Final | XIRR | Max DD | XIRR/DD | Avg Net | Avg Gross | Max Short | Ruined |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|---|")
    for _, row in metrics.iterrows():
        lines.append(
            f"| {row['strategy']} | ${row['final_value']:,.0f} | {row['xirr']:.1%} | {row['max_drawdown']:.1%} | "
            f"{row['xirr_over_abs_max_drawdown']:.2f} | {row['avg_net_exposure']:.1%} | "
            f"{row['avg_gross_exposure']:.1%} | {row['max_short_exposure']:.1%} | "
            f"{row['ruined']} |"
        )
    lines.append("")
    lines.append("## Latest Target Exposures")
    lines.append("")
    lines.append("| Strategy | Long | Short | Net | Gross | Hedge Active |")
    lines.append("|---|---:|---:|---:|---:|---|")
    for _, row in latest_targets.iterrows():
        lines.append(
            f"| {row['strategy']} | {row['long_exposure']:.1%} | {row['short_exposure']:.1%} | "
            f"{row['net_exposure']:.1%} | {row['gross_exposure']:.1%} | {row['hedge_active']} |"
        )
    lines.append("")
    lines.append("## Interpretation")
    lines.append("")
    lines.append("- If a short overlay reduces drawdown but also materially reduces XIRR, it is acting as insurance, not alpha.")
    lines.append("- A 10x short overlay can work mathematically only if tightly budgeted; shorting the whole reserve at 10x can be account-ending in fast rebounds.")
    lines.append("- This model uses daily-rebalanced exposure math, not broker-specific margin calls, locate availability, tax effects, or intraday liquidation.")
    lines.append("")
    lines.append("## Files")
    lines.append("")
    lines.append("- `metrics.csv`")
    lines.append("- `daily_equity_curves.csv`")
    lines.append("- `daily_exposures.csv`")
    lines.append("- `latest_targets.csv`")
    lines.append("- `plots/equity_curves.png`")
    lines.append("- `plots/net_exposures.png`")
    out_dir.joinpath("report.md").write_text("\n".join(lines), encoding="utf-8")


def default_strategies() -> list[StrategyConfig]:
    return [
        StrategyConfig("Plain DCA 100% QQQ", "plain", use_drawdown_ladder=False),
        StrategyConfig("Regime DCA, no short", "regime"),
        StrategyConfig("Budget short x3", "budget_short", leverage=3.0, max_short_exposure=1.0),
        StrategyConfig("Budget short x5", "budget_short", leverage=5.0, max_short_exposure=1.0),
        StrategyConfig("Budget short x10", "budget_short", leverage=10.0, max_short_exposure=1.0),
        StrategyConfig("Aggressive reserve short x3", "reserve_short", leverage=3.0, max_short_exposure=10.0),
        StrategyConfig("Aggressive reserve short x5", "reserve_short", leverage=5.0, max_short_exposure=10.0),
        StrategyConfig("Aggressive reserve short x10", "reserve_short", leverage=10.0, max_short_exposure=10.0),
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Backtest QQQ DCA with leveraged short overlays during risk-off regimes.")
    parser.add_argument("--dataset-path", type=Path, default=DEFAULT_DATASET_PATH)
    parser.add_argument("--signal-path", type=Path, default=DEFAULT_SIGNAL_PATH)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    parser.add_argument("--initial-capital", type=float, default=10_000.0)
    parser.add_argument("--monthly-contribution", type=float, default=1_000.0)
    parser.add_argument("--trading-cost-bps", type=float, default=3.0)
    parser.add_argument("--margin-borrow-rate", type=float, default=0.055)
    parser.add_argument("--short-borrow-rate", type=float, default=0.02)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)
    plots_dir = args.out_dir / "plots"
    plots_dir.mkdir(parents=True, exist_ok=True)

    dataset, signals = load_inputs(args.dataset_path, args.signal_path)
    first_valid = signals["target_equity_allocation"].first_valid_index()
    if first_valid is None:
        raise RuntimeError("No valid target_equity_allocation rows found in signal file.")
    close = pd.to_numeric(dataset["qqq_close"], errors="coerce").dropna()

    curves: dict[str, pd.DataFrame] = {}
    cashflows: dict[str, list[tuple[pd.Timestamp, float]]] = {}
    exposure_frames = []
    latest_rows = []
    for config in default_strategies():
        targets = build_targets(dataset.loc[close.index], signals, config)
        curve, flows = simulate_strategy(
            close,
            targets,
            name=config.name,
            start_date=pd.Timestamp(first_valid),
            initial_capital=args.initial_capital,
            monthly_contribution=args.monthly_contribution,
            trading_cost_bps=args.trading_cost_bps,
            margin_borrow_rate=args.margin_borrow_rate,
            short_borrow_rate=args.short_borrow_rate,
        )
        curves[config.name] = curve
        cashflows[config.name] = flows
        exposure = curve[["long_exposure", "short_exposure", "net_exposure", "gross_exposure", "hedge_active", "execution_state"]].copy()
        exposure.insert(0, "strategy", config.name)
        exposure_frames.append(exposure)
        latest = exposure.iloc[-1].copy()
        latest["strategy"] = config.name
        latest_rows.append(latest)

    metrics = performance_metrics(curves, cashflows)
    equity_curves = pd.concat([curve["equity"].rename(name) for name, curve in curves.items()], axis=1)
    exposures = pd.concat(exposure_frames, axis=0)
    latest_targets = pd.DataFrame(latest_rows).reset_index(drop=True)

    metrics.to_csv(args.out_dir / "metrics.csv", index=False)
    equity_curves.to_csv(args.out_dir / "daily_equity_curves.csv", index_label="date")
    exposures.to_csv(args.out_dir / "daily_exposures.csv", index_label="date")
    latest_targets.to_csv(args.out_dir / "latest_targets.csv", index=False)
    summary = {
        "source_dataset": str(args.dataset_path),
        "source_signal": str(args.signal_path),
        "start_date": first_valid,
        "end_date": close.index[-1],
        "initial_capital": args.initial_capital,
        "monthly_contribution": args.monthly_contribution,
        "trading_cost_bps": args.trading_cost_bps,
        "margin_borrow_rate": args.margin_borrow_rate,
        "short_borrow_rate": args.short_borrow_rate,
    }
    (args.out_dir / "summary.json").write_text(json.dumps(summary, indent=2, default=_json_default), encoding="utf-8")

    plot_equity(curves, plots_dir / "equity_curves.png")
    plot_exposures(curves, plots_dir / "net_exposures.png")
    write_report(args.out_dir, metrics, latest_targets, args)

    print(f"Wrote leveraged short overlay backtest to {args.out_dir}")
    print(metrics[["strategy", "final_value", "xirr", "max_drawdown", "max_short_exposure", "ruined"]].to_string(index=False))


if __name__ == "__main__":
    main()
